server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml      #mybatis  配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities  #所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml                     #mapper映射文件

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /**


  application:
    name: microservicecloud-dept
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver     #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化连接数
      max-total: 5         #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false



#  rabbitmq:
#    host: 116.196.107.214
#    port: 5672
#    username: forum
#    password: forum123
#    virtual-host: forum
#
##redis配置
#  redis:
#    host: 116.196.107.217
#    port: 6379
#    password: lanxj-f
#    timeout: 10000
#    database: 0
#    pool:
#      max-active: 10
#      max-idle: 8
#      min-idle: 2
#      max-wait: 100

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #defaultZone: http://localhost:7001/eureka 单机
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


